package com.currencyfair.minfraud.model;

import java.util.Map;

/**
 * Interface for value objects that generate parameters.
 * @since 1.0.0
 */
public interface ParamSource {
    /**
     * Put any parameters generated by this source into the supplied
     * <tt>params</tt> map. Null-valued parameters should not be added,
     * they should simply be omitted.
     * @param params The map to add parameters to.
     */
    void putParams(Map<String, String> params);
}
